version: '3'

services:

  db:
    image: postgres:16.2
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=corentin
      - POSTGRES_PASSWORD=password

  poll:
    build: poll/
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - db
    networks:
      - poll-tier
    restart: on-failure

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: on-failure

  result:
    build: result/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=corentin
      - POSTGRES_PASSWORD=password
    depends_on:
      # - db
      db:
        condition: service_started
    ports:
      - "5001:80"
    networks:
      - result-tier
    restart: on-failure

  worker:
    build: worker/
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=corentin
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
      - redis
    networks:
      - back-tier
    restart: on-failure

networks:

  poll-tier:

  result-tier:

  back-tier:

volumes:
  db-data:
